("""UPDATE DEVICES
SET DEVICE_TYPE = 'TDB'
WHERE LOWER(NAME) LIKE '%thread%' AND LOWER(NAME) LIKE '%plug%';""")

("""UPDATE DEVICES
SET DEVICE_TYPE = 'TDA'
WHERE LOWER(NAME) LIKE '%thread%' AND LOWER(NAME) LIKE '%ring%';""")   

("""UPDATE DEVICES
SET DEVICE_TYPE = 'CAL'
WHERE LOWER(NAME) LIKE '%caliper%';""")   

("""UPDATE DEVICES
SET DEVICE_TYPE = 'MIC'
WHERE LOWER(NAME) LIKE '%micrometer%';""")   

("""UPDATE DEVICES
SET DEVICE_TYPE = 'CMM'
WHERE LOWER(NAME) LIKE '%cmm%';""")   

("""UPDATE DEVICES
SET DEVICE_TYPE = 'THM'
WHERE LOWER(NAME) LIKE '%thermometer%';""")  

("""UPDATE DEVICES
SET DEVICE_TYPE = 'PG'
WHERE LOWER(NAME) LIKE '%pressure gauge%' OR LOWER(NAME) LIKE '%pressure gage%';""")  

("""UPDATE DEVICES
SET DEVICE_TYPE = 'TMR'
WHERE LOWER(NAME) LIKE '%stop watch%' OR LOWER(NAME) LIKE '%stopwatch%';""")  

("""UPDATE DEVICES
SET DEVICE_TYPE = 'RFR'
WHERE LOWER(NAME) LIKE '%refractometer%';""")  

("""UPDATE DEVICES
SET DEVICE_TYPE = 'CUP'
WHERE LOWER(NAME) LIKE '%cup%';""")  

("""UPDATE DEVICES
SET DEVICE_TYPE = 'TQ'
WHERE LOWER(NAME) LIKE '%torque%' AND LOWER(NAME) LIKE '%wrench%';""")  

("""UPDATE DEVICES
SET DEVICE_TYPE = 'CTR'
WHERE LOWER(NAME) LIKE '%controller%';""")  

("""UPDATE DEVICES
SET DEVICE_TYPE = 'MON'
WHERE LOWER(NAME) LIKE '%monitor%';""") 

("""UPDATE DEVICES
SET DEVICE_TYPE = 'PRB'
WHERE LOWER(NAME) LIKE '%probe%';""") 

("""UPDATE DEVICES
SET DEVICE_TYPE = 'CSK'
WHERE LOWER(NAME) LIKE '%countersink%';""")

("""UPDATE DEVICES
SET DEVICE_TYPE = 'IND'
WHERE LOWER(NAME) LIKE '%indicator%';""")

("""UPDATE DEVICES
SET DEVICE_TYPE = 'HT'
WHERE LOWER(NAME) LIKE '%hardness tester%';""")

("""UPDATE DEVICES
SET DEVICE_TYPE = 'RCR'
WHERE LOWER(NAME) LIKE '%recorder%';""")